from tkinter import *
root = Tk()
root.title("frame practice")
myframe = Frame(root, bg='red', width=300, height=200)
mylabel = Label(myframe, text='This is top', fg= 'black', bg='red', justify=LEFT)
mylabel.pack(padx=100, pady= 100)
myframe.pack(side=TOP)
frame2 = Frame(root, bg='black', width=300, height=200)
label2 = Label(frame2, text='This is bottom', fg= 'white', bg='black', justify=LEFT)
label2.pack(padx=100, pady= 100)
frame2.pack(side=BOTTOM)
frame3 = Frame(root, bg='blue', width=300, height=200)
label3 = Label(frame3, text='This is left', fg= 'white', bg='blue', justify=LEFT)
label3.pack(padx=100, pady= 100)
frame3.pack(side=LEFT)
frame4 = Frame(root, bg='yellow', width=300, height=200)
label4 = Frame(frame4,bg='black',width=20, height=170)
label4.pack(padx=100, pady= 100)
frame4.pack(side=RIGHT)
mainloop()